### ISSUE TITLE
Minimum editor height defined with weird prefix

### ISSUE THREAD

**Issue by bologer** [bizley/yii2-quill#9] opened 2019-09-21 10:53 UTC
See screenshot: 

![image](https://user-images.githubusercontent.com/9879933/65372331-cf10aa80-dc6e-11e9-9501-f7504d438d82.png)

Which does not apply minimum height of the editor: 

![image](https://user-images.githubusercontent.com/9879933/65372334-dafc6c80-dc6e-11e9-8d86-9b251d2ff125.png)

**Comment by bologer** [comment] 2019-09-21 10:56
Overriding options as the following helped: 

```php 
'options' => [
                    'style' => 'min-height:250px;'
                ]
```

**Comment by bizley** [comment] 2019-09-23 06:52
Could you paste here your widget configuration?

**Comment by bizley** [comment] 2019-09-28 07:56
Since I can not reproduce it I'm closing this issue. Feel free to reopen it if needed.

**Closed by bizley** 2019-09-28 07:56 UTC

**Comment by flightnc** [comment] 2020-04-23 18:42
just as an FYI, to combine with a couple of things from above, this is the code I used:
```
<?= $form->field($model, 'message')->widget(\bizley\quill\Quill::className(), 
            [
                'toolbarOptions' => 'BASIC',
                'options' =>[
                    'style' => 'min-height:250px;'
                ]
            ]
        );
    ?>
```
